-- Seed morphemes (prefixes, roots, suffixes)

INSERT INTO morphemes (morpheme, type, meaning, origin) VALUES
-- Prefixes
('a-', 'prefix', 'not, without', 'Greek'),
('ab-', 'prefix', 'away from', 'Latin'),
('ad-', 'prefix', 'to, toward', 'Latin'),
('anti-', 'prefix', 'against', 'Greek'),
('auto-', 'prefix', 'self', 'Greek'),
('bene-', 'prefix', 'good, well', 'Latin'),
('bi-', 'prefix', 'two', 'Latin'),
('circum-', 'prefix', 'around', 'Latin'),
('co-', 'prefix', 'together, with', 'Latin'),
('contra-', 'prefix', 'against', 'Latin'),
('de-', 'prefix', 'down, away', 'Latin'),
('dis-', 'prefix', 'not, apart', 'Latin'),
('eu-', 'prefix', 'good, well', 'Greek'),
('ex-', 'prefix', 'out of, former', 'Latin'),
('extra-', 'prefix', 'beyond', 'Latin'),
('hyper-', 'prefix', 'over, excessive', 'Greek'),
('in-', 'prefix', 'not, into', 'Latin'),
('inter-', 'prefix', 'between', 'Latin'),
('intra-', 'prefix', 'within', 'Latin'),
('mal-', 'prefix', 'bad', 'Latin'),
('mis-', 'prefix', 'wrong', 'Old English'),
('mono-', 'prefix', 'one', 'Greek'),
('multi-', 'prefix', 'many', 'Latin'),
('neo-', 'prefix', 'new', 'Greek'),
('non-', 'prefix', 'not', 'Latin'),
('omni-', 'prefix', 'all', 'Latin'),
('pan-', 'prefix', 'all', 'Greek'),
('peri-', 'prefix', 'around', 'Greek'),
('poly-', 'prefix', 'many', 'Greek'),
('post-', 'prefix', 'after', 'Latin'),
('pre-', 'prefix', 'before', 'Latin'),
('pro-', 'prefix', 'forward, in favor of', 'Latin'),
('re-', 'prefix', 'again, back', 'Latin'),
('semi-', 'prefix', 'half', 'Latin'),
('sub-', 'prefix', 'under', 'Latin'),
('super-', 'prefix', 'above, beyond', 'Latin'),
('syn-', 'prefix', 'together', 'Greek'),
('trans-', 'prefix', 'across', 'Latin'),
('un-', 'prefix', 'not', 'Old English'),
('uni-', 'prefix', 'one', 'Latin'),

-- Roots
('anim', 'root', 'life, spirit', 'Latin'),
('aud', 'root', 'hear', 'Latin'),
('brev', 'root', 'short', 'Latin'),
('carn', 'root', 'flesh', 'Latin'),
('chron', 'root', 'time', 'Greek'),
('clar', 'root', 'clear', 'Latin'),
('cogn', 'root', 'know', 'Latin'),
('corp', 'root', 'body', 'Latin'),
('cred', 'root', 'believe', 'Latin'),
('dict', 'root', 'say, speak', 'Latin'),
('duc', 'root', 'lead', 'Latin'),
('fac', 'root', 'make, do', 'Latin'),
('fer', 'root', 'carry', 'Latin'),
('fid', 'root', 'faith, trust', 'Latin'),
('form', 'root', 'shape', 'Latin'),
('fort', 'root', 'strong', 'Latin'),
('frag', 'root', 'break', 'Latin'),
('gen', 'root', 'birth, race', 'Greek'),
('graph', 'root', 'write', 'Greek'),
('grat', 'root', 'pleasing', 'Latin'),
('jac', 'root', 'throw', 'Latin'),
('jud', 'root', 'judge', 'Latin'),
('junct', 'root', 'join', 'Latin'),
('lect', 'root', 'read, choose', 'Latin'),
('loc', 'root', 'place', 'Latin'),
('log', 'root', 'word, study', 'Greek'),
('luc', 'root', 'light', 'Latin'),
('man', 'root', 'hand', 'Latin'),
('mit', 'root', 'send', 'Latin'),
('morph', 'root', 'form, shape', 'Greek'),
('mort', 'root', 'death', 'Latin'),
('mov', 'root', 'move', 'Latin'),
('nomen', 'root', 'name', 'Latin'),
('nov', 'root', 'new', 'Latin'),
('path', 'root', 'feeling, disease', 'Greek'),
('ped', 'root', 'foot', 'Latin'),
('phil', 'root', 'love', 'Greek'),
('phon', 'root', 'sound', 'Greek'),
('port', 'root', 'carry', 'Latin'),
('pos', 'root', 'place', 'Latin'),
('pot', 'root', 'power', 'Latin'),
('prim', 'root', 'first', 'Latin'),
('quer', 'root', 'seek, ask', 'Latin'),
('rupt', 'root', 'break', 'Latin'),
('scrib', 'root', 'write', 'Latin'),
('sect', 'root', 'cut', 'Latin'),
('sens', 'root', 'feel', 'Latin'),
('sequ', 'root', 'follow', 'Latin'),
('spec', 'root', 'look', 'Latin'),
('spir', 'root', 'breathe', 'Latin'),
('struct', 'root', 'build', 'Latin'),
('tact', 'root', 'touch', 'Latin'),
('temp', 'root', 'time', 'Latin'),
('ten', 'root', 'hold', 'Latin'),
('terr', 'root', 'earth', 'Latin'),
('tract', 'root', 'pull, drag', 'Latin'),
('val', 'root', 'worth, strength', 'Latin'),
('ven', 'root', 'come', 'Latin'),
('ver', 'root', 'true', 'Latin'),
('vid', 'root', 'see', 'Latin'),
('vit', 'root', 'life', 'Latin'),
('voc', 'root', 'call, voice', 'Latin'),
('vol', 'root', 'wish, will', 'Latin'),

-- Suffixes
('-able', 'suffix', 'capable of being', 'Latin'),
('-acy', 'suffix', 'state or quality', 'Latin'),
('-al', 'suffix', 'relating to', 'Latin'),
('-ance', 'suffix', 'state of', 'Latin'),
('-ant', 'suffix', 'one who', 'Latin'),
('-ation', 'suffix', 'action or process', 'Latin'),
('-dom', 'suffix', 'state of being', 'Old English'),
('-en', 'suffix', 'made of, to make', 'Old English'),
('-ence', 'suffix', 'state of', 'Latin'),
('-er', 'suffix', 'one who', 'Old English'),
('-ful', 'suffix', 'full of', 'Old English'),
('-ible', 'suffix', 'capable of being', 'Latin'),
('-ic', 'suffix', 'relating to', 'Greek'),
('-ion', 'suffix', 'act or process', 'Latin'),
('-ism', 'suffix', 'belief, practice', 'Greek'),
('-ist', 'suffix', 'one who practices', 'Greek'),
('-ity', 'suffix', 'state or quality', 'Latin'),
('-ive', 'suffix', 'tending to', 'Latin'),
('-less', 'suffix', 'without', 'Old English'),
('-ly', 'suffix', 'in the manner of', 'Old English'),
('-ment', 'suffix', 'result of action', 'Latin'),
('-ness', 'suffix', 'state of being', 'Old English'),
('-ology', 'suffix', 'study of', 'Greek'),
('-ous', 'suffix', 'full of', 'Latin'),
('-ship', 'suffix', 'state of being', 'Old English'),
('-tion', 'suffix', 'act or state', 'Latin'),
('-ty', 'suffix', 'state of', 'Latin'),
('-ure', 'suffix', 'act or process', 'Latin'),
('-ward', 'suffix', 'in the direction of', 'Old English'),
('-y', 'suffix', 'characterized by', 'Old English');
