-- Seed vocabulary words (literary/SAT level)

INSERT INTO words (word, part_of_speech, pronunciation, etymology, difficulty) VALUES
('aberrant', 'adjective', 'uh-BER-uhnt', 'Latin aberrantem, present participle of aberrare "to wander away"', 3),
('abstruse', 'adjective', 'ab-STROOS', 'Latin abstrusus "hidden, concealed"', 4),
('acerbic', 'adjective', 'uh-SUR-bik', 'Latin acerbus "sour, bitter"', 3),
('acumen', 'noun', 'AK-yoo-men', 'Latin acumen "a point, sharpness"', 3),
('admonish', 'verb', 'ad-MON-ish', 'Latin admonere "to advise, remind"', 2),
('aesthetic', 'adjective', 'es-THET-ik', 'Greek aisthetikos "of sense perception"', 2),
('alacrity', 'noun', 'uh-LAK-ri-tee', 'Latin alacritas "liveliness, eagerness"', 3),
('ameliorate', 'verb', 'uh-MEEL-yuh-rayt', 'Latin melior "better"', 4),
('anachronism', 'noun', 'uh-NAK-ruh-niz-um', 'Greek ana "against" + chronos "time"', 3),
('anathema', 'noun', 'uh-NATH-uh-muh', 'Greek anathema "a thing devoted to evil"', 4),
('antithesis', 'noun', 'an-TITH-uh-sis', 'Greek antitithenai "to set against"', 3),
('apocryphal', 'adjective', 'uh-POK-ruh-ful', 'Greek apokryphos "hidden, obscure"', 4),
('archaic', 'adjective', 'ar-KAY-ik', 'Greek arkhaikos "old-fashioned"', 2),
('arduous', 'adjective', 'AR-joo-us', 'Latin arduus "steep, difficult"', 2),
('ascetic', 'adjective', 'uh-SET-ik', 'Greek asketikos "rigorously self-disciplined"', 3),
('aspersion', 'noun', 'uh-SPUR-zhun', 'Latin aspergere "to sprinkle"', 4),
('assiduous', 'adjective', 'uh-SIJ-oo-us', 'Latin assiduus "constantly present"', 3),
('auspicious', 'adjective', 'aw-SPISH-us', 'Latin auspicium "divination by birds"', 2),
('austere', 'adjective', 'aw-STEER', 'Greek austeros "harsh, bitter"', 2),
('avarice', 'noun', 'AV-uh-ris', 'Latin avaritia "greed"', 3),
('bellicose', 'adjective', 'BEL-i-kohs', 'Latin bellicosus "warlike"', 3),
('benevolent', 'adjective', 'buh-NEV-uh-lunt', 'Latin bene "well" + volens "wishing"', 2),
('brusque', 'adjective', 'brusk', 'French brusque "lively, fierce"', 2),
('cacophony', 'noun', 'kuh-KOF-uh-nee', 'Greek kakophonia "bad sound"', 3),
('candor', 'noun', 'KAN-der', 'Latin candor "whiteness, purity"', 2),
('capricious', 'adjective', 'kuh-PRISH-us', 'Italian capriccio "sudden start"', 3),
('catalyst', 'noun', 'KAT-uh-list', 'Greek katalysis "dissolution"', 2),
('caustic', 'adjective', 'KAW-stik', 'Greek kaustikos "capable of burning"', 3),
('circumlocution', 'noun', 'sur-kum-loh-KYOO-shun', 'Latin circum "around" + loqui "to speak"', 4),
('clandestine', 'adjective', 'klan-DES-tin', 'Latin clandestinus "secret, hidden"', 3),
('cogent', 'adjective', 'KOH-junt', 'Latin cogere "to drive together"', 3),
('complacent', 'adjective', 'kum-PLAY-sunt', 'Latin complacere "to be pleasing"', 2),
('concomitant', 'adjective', 'kun-KOM-i-tunt', 'Latin concomitari "to accompany"', 4),
('conflagration', 'noun', 'kon-fluh-GRAY-shun', 'Latin conflagrare "to burn up"', 4),
('conundrum', 'noun', 'kuh-NUN-drum', 'Origin unknown, possibly mock Latin', 2),
('corroborate', 'verb', 'kuh-ROB-uh-rayt', 'Latin corroborare "to strengthen"', 3),
('credulous', 'adjective', 'KREJ-uh-lus', 'Latin credulus "easily believing"', 3),
('deleterious', 'adjective', 'del-uh-TEER-ee-us', 'Greek deleterios "destructive"', 4),
('denigrate', 'verb', 'DEN-i-grayt', 'Latin denigrare "to blacken"', 3),
('deride', 'verb', 'di-RYDE', 'Latin deridere "to mock"', 2),
('desultory', 'adjective', 'DES-ul-tor-ee', 'Latin desultorius "superficial"', 4),
('dichotomy', 'noun', 'dye-KOT-uh-mee', 'Greek dichotomia "a cutting in two"', 3),
('didactic', 'adjective', 'dye-DAK-tik', 'Greek didaktikos "apt at teaching"', 3),
('diffident', 'adjective', 'DIF-i-dunt', 'Latin diffidere "to mistrust"', 3),
('dilatory', 'adjective', 'DIL-uh-tor-ee', 'Latin dilatorius "tending to delay"', 4),
('disparage', 'verb', 'di-SPAR-ij', 'Old French desparagier "to marry unequally"', 2),
('dissemble', 'verb', 'di-SEM-bul', 'Latin dissimulare "to disguise"', 3),
('ebullient', 'adjective', 'i-BUL-yunt', 'Latin ebullire "to boil over"', 3),
('eclectic', 'adjective', 'i-KLEK-tik', 'Greek eklektikos "selective"', 2),
('efficacious', 'adjective', 'ef-i-KAY-shus', 'Latin efficax "powerful, effective"', 4),
('egregious', 'adjective', 'i-GREE-jus', 'Latin egregius "distinguished, eminent"', 3),
('elucidate', 'verb', 'i-LOO-si-dayt', 'Latin elucidare "to make clear"', 3),
('emulate', 'verb', 'EM-yoo-layt', 'Latin aemulari "to rival"', 2),
('enervate', 'verb', 'EN-ur-vayt', 'Latin enervare "to weaken"', 4),
('enigmatic', 'adjective', 'en-ig-MAT-ik', 'Greek ainigma "riddle"', 3),
('ephemeral', 'adjective', 'i-FEM-ur-ul', 'Greek ephemeros "lasting only a day"', 3),
('equanimity', 'noun', 'ee-kwuh-NIM-i-tee', 'Latin aequanimitas "evenness of mind"', 4),
('equivocate', 'verb', 'i-KWIV-uh-kayt', 'Latin aequivocus "of equal voice"', 3),
('erudite', 'adjective', 'ER-yoo-dyte', 'Latin eruditus "instructed, learned"', 3),
('esoteric', 'adjective', 'es-uh-TER-ik', 'Greek esoterikos "belonging to an inner circle"', 3),
('euphemism', 'noun', 'YOO-fuh-miz-um', 'Greek euphemismos "use of a favorable word"', 2),
('exacerbate', 'verb', 'ig-ZAS-ur-bayt', 'Latin exacerbare "to irritate"', 3),
('exculpate', 'verb', 'EK-skul-payt', 'Latin ex "out" + culpa "blame"', 4),
('exigent', 'adjective', 'EK-si-junt', 'Latin exigere "to demand"', 4),
('expedient', 'adjective', 'ik-SPEE-dee-unt', 'Latin expedire "to free from fetters"', 2),
('extenuate', 'verb', 'ik-STEN-yoo-ayt', 'Latin extenuare "to make thin"', 4),
('facetious', 'adjective', 'fuh-SEE-shus', 'Latin facetia "jest, witticism"', 3),
('fallacious', 'adjective', 'fuh-LAY-shus', 'Latin fallax "deceptive"', 3),
('fastidious', 'adjective', 'fa-STID-ee-us', 'Latin fastidiosus "disdainful"', 3),
('fecund', 'adjective', 'FEK-und', 'Latin fecundus "fruitful"', 4),
('garrulous', 'adjective', 'GAR-uh-lus', 'Latin garrulus "talkative"', 3),
('gregarious', 'adjective', 'gri-GAIR-ee-us', 'Latin gregarius "of a flock"', 2),
('hackneyed', 'adjective', 'HAK-need', 'From Hackney, where horses were raised', 3),
('hegemony', 'noun', 'hi-JEM-uh-nee', 'Greek hegemonia "leadership"', 4),
('iconoclast', 'noun', 'eye-KON-uh-klast', 'Greek eikonoklastes "image breaker"', 3),
('impecunious', 'adjective', 'im-pi-KYOO-nee-us', 'Latin in "not" + pecunia "money"', 4),
('impervious', 'adjective', 'im-PUR-vee-us', 'Latin in "not" + pervius "passable"', 2),
('implacable', 'adjective', 'im-PLAK-uh-bul', 'Latin in "not" + placare "to calm"', 3),
('inchoate', 'adjective', 'in-KOH-it', 'Latin inchoare "to begin"', 4),
('indefatigable', 'adjective', 'in-di-FAT-i-guh-bul', 'Latin in "not" + defatigare "to tire out"', 4),
('ingenuous', 'adjective', 'in-JEN-yoo-us', 'Latin ingenuus "native, freeborn"', 3),
('inimical', 'adjective', 'i-NIM-i-kul', 'Latin inimicus "enemy"', 3),
('insidious', 'adjective', 'in-SID-ee-us', 'Latin insidiosus "cunning"', 3),
('intransigent', 'adjective', 'in-TRAN-si-junt', 'Spanish intransigente "uncompromising"', 4),
('inundate', 'verb', 'IN-un-dayt', 'Latin inundare "to overflow"', 2),
('invective', 'noun', 'in-VEK-tiv', 'Latin invectivus "attacking"', 3),
('laconic', 'adjective', 'luh-KON-ik', 'Greek Lakonikos "Spartan"', 3),
('loquacious', 'adjective', 'loh-KWAY-shus', 'Latin loquax "talkative"', 3),
('lucid', 'adjective', 'LOO-sid', 'Latin lucidus "bright, clear"', 2),
('magnanimous', 'adjective', 'mag-NAN-uh-mus', 'Latin magnus "great" + animus "soul"', 3),
('malevolent', 'adjective', 'muh-LEV-uh-lunt', 'Latin male "ill" + volens "wishing"', 3),
('mendacious', 'adjective', 'men-DAY-shus', 'Latin mendax "lying"', 4),
('meticulous', 'adjective', 'muh-TIK-yoo-lus', 'Latin meticulosus "fearful"', 2),
('mollify', 'verb', 'MOL-uh-fye', 'Latin mollificare "to make soft"', 3),
('nefarious', 'adjective', 'ni-FAIR-ee-us', 'Latin nefarius "wicked"', 3),
('obdurate', 'adjective', 'OB-doo-rit', 'Latin obdurare "to harden"', 4),
('obsequious', 'adjective', 'ub-SEE-kwee-us', 'Latin obsequiosus "compliant"', 4);

-- Continue with more words
INSERT INTO words (word, part_of_speech, pronunciation, etymology, difficulty) VALUES
('obviate', 'verb', 'OB-vee-ayt', 'Latin obviare "to meet, withstand"', 4),
('ostentatious', 'adjective', 'os-ten-TAY-shus', 'Latin ostentare "to display"', 3),
('panacea', 'noun', 'pan-uh-SEE-uh', 'Greek panakeia "cure-all"', 3),
('paradigm', 'noun', 'PAR-uh-dyme', 'Greek paradeigma "pattern, example"', 2),
('parsimonious', 'adjective', 'par-suh-MOH-nee-us', 'Latin parsimonia "frugality"', 4),
('paucity', 'noun', 'PAW-si-tee', 'Latin paucitas "fewness"', 3),
('pedantic', 'adjective', 'puh-DAN-tik', 'Italian pedante "teacher"', 3),
('perfidious', 'adjective', 'pur-FID-ee-us', 'Latin perfidus "faithless"', 4),
('perfunctory', 'adjective', 'pur-FUNK-tuh-ree', 'Latin perfunctorius "careless"', 3),
('pernicious', 'adjective', 'pur-NISH-us', 'Latin perniciosus "destructive"', 4),
('perspicacious', 'adjective', 'pur-spi-KAY-shus', 'Latin perspicax "sharp-sighted"', 4),
('philanthropy', 'noun', 'fi-LAN-thruh-pee', 'Greek philanthropia "love of mankind"', 2),
('phlegmatic', 'adjective', 'fleg-MAT-ik', 'Greek phlegmatikos "abounding in phlegm"', 4),
('placate', 'verb', 'PLAY-kayt', 'Latin placare "to calm"', 2),
('pragmatic', 'adjective', 'prag-MAT-ik', 'Greek pragmatikos "practical"', 2),
('precipitous', 'adjective', 'pri-SIP-i-tus', 'Latin praeceps "headlong"', 3),
('precocious', 'adjective', 'pri-KOH-shus', 'Latin praecox "ripening early"', 2),
('prescient', 'adjective', 'PRESH-unt', 'Latin praescire "to know beforehand"', 4),
('presumptuous', 'adjective', 'pri-ZUMP-choo-us', 'Latin praesumere "to take for granted"', 3),
('probity', 'noun', 'PROH-bi-tee', 'Latin probitas "uprightness"', 4),
('proclivity', 'noun', 'proh-KLIV-i-tee', 'Latin proclivitas "a tendency"', 3),
('prodigious', 'adjective', 'pruh-DIJ-us', 'Latin prodigiosus "marvelous"', 3),
('profligate', 'adjective', 'PROF-li-git', 'Latin profligatus "dissolute"', 4),
('propitious', 'adjective', 'pruh-PISH-us', 'Latin propitius "favorable"', 3),
('prosaic', 'adjective', 'proh-ZAY-ik', 'Latin prosaicus "in prose"', 3),
('pugnacious', 'adjective', 'pug-NAY-shus', 'Latin pugnax "combative"', 3),
('querulous', 'adjective', 'KWER-uh-lus', 'Latin querulus "complaining"', 4),
('quixotic', 'adjective', 'kwik-SOT-ik', 'From Don Quixote', 3),
('recalcitrant', 'adjective', 'ri-KAL-si-trunt', 'Latin recalcitrare "to kick back"', 4),
('recondite', 'adjective', 'REK-un-dyte', 'Latin reconditus "hidden, concealed"', 5),
('refractory', 'adjective', 'ri-FRAK-tuh-ree', 'Latin refractarius "stubborn"', 4),
('repudiate', 'verb', 'ri-PYOO-dee-ayt', 'Latin repudiare "to reject"', 3),
('reticent', 'adjective', 'RET-i-sunt', 'Latin reticere "to keep silent"', 2),
('sagacious', 'adjective', 'suh-GAY-shus', 'Latin sagax "wise"', 4),
('sanguine', 'adjective', 'SANG-gwin', 'Latin sanguineus "of blood"', 3),
('sardonic', 'adjective', 'sar-DON-ik', 'Greek sardonios "bitter, scornful"', 3),
('sedulous', 'adjective', 'SEJ-oo-lus', 'Latin sedulus "diligent"', 4),
('spurious', 'adjective', 'SPYOOR-ee-us', 'Latin spurius "illegitimate"', 3),
('surreptitious', 'adjective', 'sur-up-TISH-us', 'Latin surripere "to snatch secretly"', 3),
('sycophant', 'noun', 'SIK-uh-funt', 'Greek sykophantes "informer"', 3),
('taciturn', 'adjective', 'TAS-i-turn', 'Latin taciturnus "silent"', 3),
('temerity', 'noun', 'tuh-MER-i-tee', 'Latin temeritas "rashness"', 4),
('tenacious', 'adjective', 'tuh-NAY-shus', 'Latin tenax "holding fast"', 2),
('trepidation', 'noun', 'trep-i-DAY-shun', 'Latin trepidare "to tremble"', 3),
('truculent', 'adjective', 'TRUK-yoo-lunt', 'Latin truculentus "fierce"', 4),
('ubiquitous', 'adjective', 'yoo-BIK-wi-tus', 'Latin ubique "everywhere"', 2),
('unctuous', 'adjective', 'UNK-choo-us', 'Latin unctuosus "oily"', 4),
('vacillate', 'verb', 'VAS-uh-layt', 'Latin vacillare "to sway"', 3),
('venal', 'adjective', 'VEE-nul', 'Latin venalis "for sale"', 4),
('verbose', 'adjective', 'vur-BOHS', 'Latin verbosus "full of words"', 2),
('vicarious', 'adjective', 'vye-KAIR-ee-us', 'Latin vicarius "substituted"', 3),
('vindicate', 'verb', 'VIN-di-kayt', 'Latin vindicare "to claim, avenge"', 2),
('vitriolic', 'adjective', 'vi-tree-OL-ik', 'Latin vitriolum "sulfuric acid"', 3),
('vociferous', 'adjective', 'voh-SIF-ur-us', 'Latin vociferari "to cry out"', 3),
('zealous', 'adjective', 'ZEL-us', 'Greek zelos "eager rivalry"', 2);
